name: Build ISO

on:
  push:
      paths-ignore:
      - '**.md'
  pull_request:
        paths-ignore:
        - '**.md'
  

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shadowreaperscpf/kronosos-titan:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Sanity check, if we are on KronosOS environment
        run: |
          cat /etc/os-release          
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso
      - name: Build ISO File
        run: |
          mkarchiso -v .
          find out/
      - uses: actions/upload-artifact@v2
        with:
          name: KronosOS
          path: out/*.iso
